### DISCUSSION TITLE
성능테스트

### DISCUSSION THREAD

**Discussion by kimziou77** [prgrms-web-devcourse/Team-Books-CheckMoi-BE#262] [General]
## 사용 툴

|Artillery!|![image](https://user-images.githubusercontent.com/41179265/185605273-9e816209-d2b8-464c-831f-1a7214ced9aa.png)
|---|---|

### 선택 이유
이전에 학습했던 내용중 Artillery에 대한 부분이 있었지만 실제 프로젝트에 적용해본 적이 없어 사용해보고 싶었다. 사용법이 간단해서 빠르게 테스트 해보기 좋다고 생각되었다.

## 환경
- AWS t2.small 
- Ubuntu 18.04

## 테스트 시나리오
```yml
scenarios:
  - name: "포스트 작성"
    flow:
      - post:
          url: "/api/posts"
          headers:
            Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiTE9HSU4iLCJ1c2VySWQiOjEsImlhdCI6MTY2MDIwMDg4NywiZXhwIjoxNjYwMjA0NDg3fQ.-r6Xl-YHecs_SFPqrqtCZ1U35nwpo_jqHg1dVALGGlQ"
          json:
            title: "포스트 작성 성능 테스트"
            content: "성능 테스트"
            category: "GENERAL"
            studyId: 1
```

Id |Config | Latency
--|--|--
1 |![image](https://user-images.githubusercontent.com/41179265/185605984-8c5cc070-a903-4032-8a4a-7dc1d43df9dd.png)|![image](https://user-images.githubusercontent.com/41179265/185606151-dc803a38-b86d-42f5-8d8a-1fc0d78d37a8.png)
2|![image](https://user-images.githubusercontent.com/41179265/185606298-d41c5190-99a5-47b8-a30d-5ef6aca6ca52.png)|![image](https://user-images.githubusercontent.com/41179265/185606423-24cbb0ea-b5b5-43d0-a976-7cdf2fc4e66a.png)
3|![image](https://user-images.githubusercontent.com/41179265/185606327-0f3751cb-a849-44d7-8494-4a34f049257d.png)|![image](https://user-images.githubusercontent.com/41179265/185606511-31ffa88c-e120-4f3e-8639-7c06aa3eb738.png)
4|![image](https://user-images.githubusercontent.com/41179265/185606579-22c89664-4e17-43d1-b215-d186bd79f51f.png)|![image](https://user-images.githubusercontent.com/41179265/185606634-5ac0ddab-2950-40ad-8469-0ff14bfbe525.png)

## 생각
툴에 대한 사용은 대충 알았으니 어느 부분을 테스트 해보면 좋을지 생각해보자
서비스 가용인원을 파악하는데 좋지 않을까?

## 추가
어느 쯤 병목이 걸리는지 알아볼 수 있다고 한다.
Application 단 에서는
- 스레드 동기화
- application 메모리 정도
- 얘가 어느정도까지 버티는가? 최소 어느정도 TPS 이 처리가 가능한지

RDS가 생각보다 비용이 많이 비싸다고 한다.
추가로 AWS 가격정책을 알아보면 좋을 것 같다.
